# Matrix Transpose and Inverse Demonstration In Python
## Multiple Linear Regression: Calculating Parameters and Standard Errors Using Mathematical Estimation

#### Using House Price Data 

### Background: 
The data has 506 cases where each case is a location in Boston. The “median housing price” is a target variable. The data has many other variables related to environment,education,,crime etc.which can influence the housing prices in the specific location

### Objectives :
1) Perform Linear Regression using ols function 
2)   Estimate parameters using matrix operations

### Data Description

| Column Name | Column Description |
|-------------|--------------------|
| CRIM | per capita crime rate by town |
| ZN | proportion of residential land zoned for lots over 25,000 sq ft |
| INDUS | proportion of non-retail business acres per town (%) |
| CHAS | Charles River dummy variable (=1 if tract bounds river; 0 otherwise) |
| NOX | nitric oxides concentration (parts per 10 million) |
| RM | average number of rooms per dwelling |
| AGE | proportion of owner-occupied units built prior to 1940 (%) |
| DIS | weighted distances to five Boston employment centres |
| RAD | index of accessibility to radial highways |
| TAX | full-value property-tax rate per dollar 10,000 |
| PTRATIO | pupil-teacher ratio by town |
| LSAT | % lower status of the population |
| MEDV | median value of owner-occupied homes (in $1000s) |



### Import Libraries

In [1]:
import numpy as np
import pandas as pd  
import statsmodels.formula.api as smf

### Import Data

In [2]:
df = pd.read_csv('Housing Prices.csv')
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO  LSTAT  MEDV  
0       15.3   4.98  24.0  
1       17.8   9.14  21.6  
2       17.8   4.03  34.7  
3       18.7   2.94  33.4  
4       18.7   5.33  36.2  
..       ...    ...   ...  
501     21.0   9.67  22.4  
502     21.0   9.08  20.6  
503     21.0   5.64  23.9  
504     21.0   6.48  22.0  
505     21.0   7.88  11.9  

[506 rows x 13 columns]

### Part 1 :  Perform Linear Regression using ols function


In [3]:
model = smf.ols('MEDV~CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO+LSTAT',data=df).fit()

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.734
Model:                            OLS   Adj. R-squared:                  0.728
Method:                 Least Squares   F-statistic:                     113.5
Date:                Wed, 03 Dec 2025   Prob (F-statistic):          2.23e-133
Time:                        18:56:26   Log-Likelihood:                -1504.9
No. Observations:                 506   AIC:                             3036.
Df Residuals:                     493   BIC:                             3091.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     41.6173      4.936      8.431      0.000      31.919      51.316
CRIM          -0.1214      0.033     -3.678      0.000      -0.186      -0.057
ZN             0.0470      0.014      3.384      0.001       0.020       0.074
INDUS          0.0135      0.062      0.217      0.829      -0.109       0.136
CHAS           2.8400      0.870      3.264      0.001       1.131       4.549
NOX          -18.7580      3.851     -4.870      0.000     -26.325     -11.191
RM             3.6581      0.420      8.705      0.000       2.832       4.484
AGE            0.0036      0.013      0.271      0.787      -0.023       0.030
DIS           -1.4908      0.202     -7.394      0.000      -1.887      -1.095
RAD            0.2894      0.067      4.325      0.000       0.158       0.421
TAX           -0.0127      0.004     -3.337      0.001      -0.020      -0.005
PTRATIO       -0.9375      0.132     -7.091      0.000      -1.197      -0.678
LSTAT         -0.5520      0.051    -10.897      0.000      -0.652      -0.452
==============================================================================
Omnibus:                      171.096   Durbin-Watson:                   1.077
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              709.937
Skew:                           1.477   Prob(JB):                    6.90e-155
Kurtosis:                       7.995   Cond. No.                     1.17e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.17e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### Part 2 :  Estimate parameters using matrix operations


### 2.1 Create Matrix x and y

In [4]:
y = df['MEDV']
y_vector = y.to_numpy().reshape(-1,1) #-1 is used to simplify the reshaping process and ensure that the array is reshaped correctly without manually specifying each dimension size
print(y_vector[:5])

[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]]


In [5]:
# X matrix (independent variables)
x = df[['CRIM','ZN','INDUS','CHAS','NOX','RM',
        'AGE','DIS','RAD','TAX','PTRATIO','LSTAT']]
df = x.to_numpy()
dx = np.ones((len(df),1))
x_matrix = np.concatenate((dx,df),axis=1)

print(x_matrix[:5])

[[1.0000e+00 6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01
  6.5750e+00 6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01
  4.9800e+00]
 [1.0000e+00 2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01
  6.4210e+00 7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01
  9.1400e+00]
 [1.0000e+00 2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01
  7.1850e+00 6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01
  4.0300e+00]
 [1.0000e+00 3.2370e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01
  6.9980e+00 4.5800e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01
  2.9400e+00]
 [1.0000e+00 6.9050e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01
  7.1470e+00 5.4200e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01
  5.3300e+00]]


In [6]:
equation1 = np.linalg.inv(np.dot(x_matrix.T,x_matrix))
equation2 = np.dot(x_matrix.T,y_vector)
beta = np.dot(equation1,equation2)
beta

array([[ 4.16172702e+01],
       [-1.21388618e-01],
       [ 4.69634633e-02],
       [ 1.34676947e-02],
       [ 2.83999338e+00],
       [-1.87580220e+01],
       [ 3.65811904e+00],
       [ 3.61071055e-03],
       [-1.49075365e+00],
       [ 2.89404521e-01],
       [-1.26819813e-02],
       [-9.37532900e-01],
       [-5.52019101e-01]])

### 2.2 Calculating variance for 𝝱 and Y then calculating standard error using variance of β<br>
$Y=Xβ + e$ <br>
$Var(Y) = Var(Xβ + e)$ <br>
Since X and β are non random variables, $Var(Xβ)=0$<br>
Therefore, $Var(Y)=Var(e)=σ^2I$<br>

### Formulas used below <br>
$e=Y-Xβ$<br>
$σ^2= e'e/n-p-1$, where n is the number of observations and p is number of independent variables



In [7]:
error = y_vector - np.dot(x_matrix,beta)
print(error[:5])

[[-6.03373805]
 [-3.45683368]
 [ 4.09181398]
 [ 4.72282052]
 [ 8.271209  ]]


In [8]:
Z = np.dot(error.T,error)
sigmasquare = Z/(len(y)-12-1)
sigmasquare

array([[23.02113349]])

In [9]:
betacapvar = sigmasquare * np.linalg.inv(np.dot(x_matrix.T,x_matrix))
betacapvar

array([[ 2.43644857e+01, -5.16966609e-03, -1.91397462e-03,
         2.10907469e-02, -1.89399480e-01, -1.04455929e+01,
        -1.48046541e+00,  4.53409925e-03, -3.63652058e-01,
         1.05822936e-01, -1.99356944e-03, -4.16065469e-01,
        -6.72466353e-02],
       [-5.16966609e-03,  1.08902624e-03, -3.95821019e-05,
         6.86048934e-05,  1.62280299e-03,  6.52301142e-03,
         1.97020464e-04,  1.83819720e-06,  7.65558248e-04,
        -6.14038224e-04,  1.10201488e-06,  1.09388138e-04,
        -2.91226640e-04],
       [-1.91397462e-03, -3.95821019e-05,  1.92629863e-04,
         9.21073236e-05, -1.85597340e-04,  1.96430238e-03,
        -9.06791310e-04,  2.22344771e-05, -1.12646865e-03,
         9.92978324e-05, -1.17635338e-05,  5.70628817e-04,
        -3.65573065e-05],
       [ 2.10907469e-02,  6.86048934e-05,  9.21073236e-05,
         3.86196486e-03, -5.48705685e-03, -6.39899197e-02,
         2.32396593e-03,  8.45220337e-07,  2.63797239e-03,
         1.15114362e-03, -1.03751525e

In [10]:
diagonal_elements = np.diag(betacapvar)
standard_error = np.sqrt(diagonal_elements)
standard_error

array([4.93603948e+00, 3.30003976e-02, 1.38791161e-02, 6.21447090e-02,
       8.70007273e-01, 3.85135466e+00, 4.20245745e-01, 1.33294366e-02,
       2.01622698e-01, 6.69078853e-02, 3.80097849e-03, 1.32206233e-01,
       5.06587629e-02])