# Basic Mathematical Operations on Vectors and Matrices Demonstration In Python

### Using House Price Data

## Background :


We are using linear regression to predict house prices based on two features: **size** and **number of rooms**. We start with an assumed set of weights and use them to calculate predicted prices. The difference between actual and predicted values gives us the **error**, and we compute **SSE (Sum of Squared Errors)** to measure how good the weights are. By trying different weights and observing which gives the **lowest SSE**, we learn how a model improves its predictions.



## Data Description

| Column Name       | Description                                                                                                                                                  |
| ----------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| **Size (100 m²)** | Represents the size of the house. The unit here is in **hundreds of square meters** |
| **Rooms**         | Number of rooms in the house                                                          |
| **Actual (€000)** | The real selling price of the house in **thousands of Euros**.        |


### Import libraries

In [1]:
import pandas as pd
import numpy as np

### Create Feature Matrix (X)

Here, we have 2 input features for each house:

1️⃣ Size of the house (in units of 100 m²)

2️⃣ Number of rooms

In [2]:
# Create matrices
X = np.array([[1.2, 3], 
              [1.5, 4], 
              [1.0, 2], 
              [2.0, 5], 
              [1.8, 4]])

print("X:")
print(X)

X:
[[1.2 3. ]
 [1.5 4. ]
 [1.  2. ]
 [2.  5. ]
 [1.8 4. ]]


### Create Weight Matrix (W)

Weights represent how important each feature is in predicting house price
(values are in €000)

- W₁ = 80 → Each additional 100 m² adds €80,000 to the price (holding  rooms constant).
- W₂ = 20 → Each additional room adds €20,000 to the price (holding size constant).


In [3]:
W = np.array([[80],   # Weight for size
              [20]])  # Weight for number of rooms

print("\nW (in €000):")
print(W)


W (in €000):
[[80]
 [20]]


### Predict House Prices using Matrix Multiplication

Prediction formula:

y^ = X * W

##### Predicted Price = (Size × Weight1) + (Rooms × Weight2)


In [4]:
y_pred = X @ W  # or np.dot(X, W)
print("\nPredicted Price (X @ W):")
print(y_pred)


Predicted Price (X @ W):
[[156.]
 [200.]
 [120.]
 [260.]
 [224.]]


### Compare with actual prices
These are the true market prices of the houses

In [5]:
Y = np.array([[151],
              [204],
              [117],
              [266],
              [222]])

print("\nActual Prices (Y):")
print(Y)
print("\nShape of Y:", Y.shape)


Actual Prices (Y):
[[151]
 [204]
 [117]
 [266]
 [222]]

Shape of Y: (5, 1)


### Calculate Vector Of Errors 

Error = Actual − Predicted

In [6]:
# Calculate error
error = Y - y_pred

print("Error:")
print(error)


Error:
[[-5.]
 [ 4.]
 [-3.]
 [ 6.]
 [-2.]]


### Calculate Sum of Squared Errors (SSE)
SSE measures how well our weights predict the actual prices

Lower SSE = Better predictions


In [11]:
SSE = error.T @ error  # Transpose of error × error

print("\nSSE:")
print(SSE)


SSE:
[[90.]]


### EXPERIMENT WITH DIFFERENT WEIGHTS

#### Try different weight combinations below and observe how SSE changes
#### Goal: Find weights that minimize SSE

In [21]:
W_new = np.array([[81],   # Your weight for size
                   [19]])  # Your weight for rooms
 
y_pred_new = X @ W_new
error_new = Y - y_pred_new
SSE_new = error_new.T @ error_new
SSE_new

array([[137.53]])

#### In this case, W = [80,20] yields lower SSE as compared to W_new [81,19]. In the next unit, we will show the computation of optimum weights