# M3 MCS - ASSIGNMENT 1

## Matrix Operations

BACKGROUND:

You are given six observations on two variables X and Y.

X=[ 49.5, 54.6, 52.8,50.3,50.8,51.6]

Y=[ 36.9,56.7,53.8,43.1,49.4,45.4]

Here Y is the dependent variable and X is the independent variable.

## QUESTIONS

1. Perform Simple Linear Regression using ols function in Python and display table of regression coefficients.

In [6]:
import pandas as pd
import statsmodels.formula.api as smf
import warnings
warnings.filterwarnings('ignore')

data = pd.DataFrame({
    'X': [49.5, 54.6, 52.8, 50.3, 50.8, 51.6],
    'Y': [36.9, 56.7, 53.8, 43.1, 49.4, 45.4]
})

model = smf.ols('Y ~ X', data=data).fit()
print(model.summary().tables[1])

                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -137.5252     40.858     -3.366      0.028    -250.966     -24.084
X              3.5867      0.791      4.532      0.011       1.389       5.784


2. Define design matrix X and target vector Y considering linear regression model with intercept


In [7]:
import numpy as np

X_val = np.array([49.5, 54.6, 52.8, 50.3, 50.8, 51.6])
Y_vec = np.array([36.9, 56.7, 53.8, 43.1, 49.4, 45.4]).reshape(-1, 1)

# Design matrix with intercept (column of 1s)
X_mat = np.column_stack((np.ones(len(X_val)), X_val))

print("Design Matrix X:\n", X_mat)
print("\nTarget Vector Y:\n", Y_vec)

Design Matrix X:
 [[ 1.  49.5]
 [ 1.  54.6]
 [ 1.  52.8]
 [ 1.  50.3]
 [ 1.  50.8]
 [ 1.  51.6]]

Target Vector Y:
 [[36.9]
 [56.7]
 [53.8]
 [43.1]
 [49.4]
 [45.4]]


3. Obtain XT Y and (X’X)-1


In [8]:
XT_Y = np.dot(X_mat.T, Y_vec)
XT_X_inv = np.linalg.inv(np.dot(X_mat.T, X_mat))

print("XT Y:\n", XT_Y)
print("\n(X'X)^-1:\n", XT_X_inv)

XT Y:
 [[  285.3]
 [14783.1]]

(X'X)^-1:
 [[ 1.55146876e+02 -3.00349243e+00]
 [-3.00349243e+00  5.82072177e-02]]


4. Obtain least square estimates of two model parameters


In [9]:
beta_hat = np.dot(XT_X_inv, XT_Y)
print("Least Square Estimates (Intercept, Slope):\n", beta_hat)

Least Square Estimates (Intercept, Slope):
 [[-137.52520373]
 [   3.58672875]]


5. Compare the answers with ols function output

In [10]:
print("OLS Function Estimates:")
print(model.params)
print("\nMatrix Calculations Estimates:")
print(f"Intercept: {beta_hat[0][0]}")
print(f"Slope:     {beta_hat[1][0]}")

OLS Function Estimates:
Intercept   -137.525204
X              3.586729
dtype: float64

Matrix Calculations Estimates:
Intercept: -137.52520372529233
Slope:     3.586728754366036
